### ISSUE TITLE
Die Verzeichnisse werden nicht komplett recursive gescannt

### ISSUE THREAD

**Issue by TimUx** [kakadoo/traco#3]
Hallo,
ich habe mal die BETA version getestet.

Hierbei ist mir aufgefallen, dass der tracosrv.pl nicht alle Verzeichnisse komplett recursive durchgeht und somit auch nicht überall ein traco.xml erstellt.

Hier ein kleiner debug output

`
[DEBUG]proccess queue item /mnt/data/tv/Pacific_Rim/2015-12-26.20.10.6-0.rec
-> traco.xml

[DEBUG]proccess queue item /mnt/data/tv/Percy_Jackson_-_Diebe_im_Olymp
-> kein traco.xml

[DEBUG]proccess queue item /mnt/data/tv/Rapunzel_-_Neu_verföhnt/2015-12-20.20.10.62-0.rec
-> traco.xml

[DEBUG]proccess queue item /mnt/data/tv/The_Karate_Kid
-> kein traco.xml

[DEBUG]proccess queue item /mnt/data/tv/The_Marine
-> kein traco.xml

[DEBUG]proccess queue item /mnt/data/tv/The_Punisher/2015-10-03.22.58.93-0.rec
-> traco.xml

[DEBUG]proccess queue item /mnt/data/tv/Transformers
-> kein traco.xml

[DEBUG]proccess queue item /mnt/data/tv/Unbreakable_-_Unzerbrechlich/2013-03-31.20.10.7-0.rec
-> traco.xml

[DEBUG]proccess queue item /mnt/data/tv/Vehicle_19
-> kein traco.xml

[DEBUG]proccess queue item /mnt/data/tv/Wolverine#3A_Weg_des_Kriegers
-> kein traco.xml

[DEBUG]proccess queue item /mnt/data/tv/ZDF-Morgenmagazin
-> kein traco.xml
`

Gruß Timo

**Comment by kakadoo** [comment]
hi

lieft zz ein anderer job von traco ?
wenn j.b. traco in einem transcode job ist so macht er nicht anders.

ansonsten gibt es noch das problem das einges sonderzeichen im path
hinderlich sind.

holger


Am 20. Mai 2016 um 10:46 schrieb TimUx <notifications@github.com>:

**Comment by TimUx** [comment]
Hallo Holger,
zu dem Zeitpunkt lief kein anderer Prozess.

Ich habe tracosrv.pl -f -vvv gestartet und zugeschaut was er so macht.

Für /mnt/data/tv/Rapunzel_-_Neu_verföhnt/2015-12-20.20.10.62-0.rec erstellt er z.B. automatisch ein traco.xml file.

Für /mnt/data/tv/Transformers erstellt er keins, hier geht er erst überhaupt nicht in das rec Verzeichnis.
Im Debug sieht man, dass er nur bis /mnt/data/tv/Transformers geht und nicht bis /mnt/data/tv/Transformers/2015-10-09.23.10.9-0.rec

Mit dem tracoadm.pl kann ich manuel ein traco.xml file in den Trasnformers Ordner anlegen.

racoadm.pl profile HD /mnt/data/tv/Transformers/2015-10-09.23.10.9-0.rec/
Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/Traco/Tracoio.pm line 298.
create /mnt/data/tv/Transformers/2015-10-09.23.10.9-0.rec/traco.xml done
create new xml file with profile HD status__createxmlfile_done
tracoadm exit with create_new_profile_done

Allerdings wird aber sowohl der status "prepare_traco_ts" und "ready" vollkommen vom tracosrv.pl ignoriert.
Ich vermute eben weil der srv nicht bis in das rec Verzeichnis runter schaut.

Bei dem Trasnformers Ordern ist ja nun wikrlich kein besonderes Sonderzeichen oder ähnliches vorhanden. ;-)

Gruß Timo

**Comment by TimUx** [comment]
Hier sieht man noch mal schön, wie ich den status ändere, der tracosrv es aber ignoriert.

server> tracoadm.pl status prepare_traco_ts /mnt/data/tv/Transformers/2015-10-09.23.10.9-0.rec
tracoadm exit with done


server> cat /mnt/data/tv/Transformers/2015-10-09.23.10.9-0.rec/traco.xml 
<status>prepare_traco_ts</status>
<vdrinfo>
<title>Transformers</title>
<episode>Transformers</episode>
<frames>25</frames>
<starttime>1444425225</starttime>
<endtime>1444435696</endtime>
<src_audio track="0">dolby digital</src_audio>
</vdrinfo>
<files>ARRAY(0x99b130)</files>
<profile name="HD">
<name>HD (1080p) Profile with UVHQ bitrate</name>
<resolution>1080p</resolution>
<container>mp4</container>
<pixel>1920</pixel>
<ypixel>1080</ypixel>
<anamorph>--loose-anamorphic</anamorph>
<modulus>8</modulus>
<quality>10000</quality>
<audiotracks>all</audiotracks>
<codec>-2 -T -e x264</codec>
<codecopts>-x ref=2:mixed-refs:bframes=2:b-pyramid=1:weightb=1:analyse=all:8x8dct=1:subme=7:me=umh:merange=24:trellis=1:no-fast-pskip=1:no-dct-decimate=1:direct=auto</codecopts>
</profile>


server> tracosrv.pl -f -vvv
[DEBUG]use configfile /etc/vdr/traco.conf
[DEBUG]debug infs xfs
[DEBUG]debug 0
[DEBUG]nice 20
[DEBUG][runexternal]exec | which HandBrakeCLI
[DEBUG]bin /usr/bin/HandBrakeCLI
[DEBUG]vdr version 2.2.0
[DEBUG][runexternal]exec | /bin/cat /proc/cpuinfo
[DEBUG]handbrake use as cpu option 3
no fork to the background
[DEBUG]proccess queue item /mnt/data/tv/10_Dinge,_die_ich_an_dir_hasse/2015-04-06.18.25.8-0.rec
[DEBUG]proccess queue item /mnt/data/tv/10_Dinge,_die_ich_an_dir_hasse/2015-04-06.18.25.8-0.rec
[DEBUG]proccess queue item /mnt/data/tv/Transformers
[DEBUG]proccess queue item /mnt/data/tv/Unbreakable_-_Unzerbrechlich/2013-03-31.20.10.7-0.rec
[DEBUG]/mnt/data/tv/10_Dinge,_die_ich_an_dir_hasse/2015-04-06.18.25.8-0.rec have status offline
[DEBUG]/mnt/data/tv/Die_Tribute_von_Panem_-_The_Hunger_Games/2015-11-08.15.14.6-0.rec have status offline
[DEBUG]/mnt/data/tv/Unbreakable_-_Unzerbrechlich/2013-03-31.20.10.7-0.rec have status offline

Gruß Timo

**Comment by kakadoo** [comment]
hi

sorry fuer die spaete antwort .

bist du sicher das du die bet hier aus dem repository nutzt ?

weile Zeile 298 Tracoio ist in der das ende von _cutfile  

Holger

**Comment by clausmuus** [comment]
Hi,
es geht um das BETA repository.
Claus

**Comment by kakadoo** [comment]
hi
ups mein fehler , musste noch die branch umstellen auf die beta.

kannst du mal bitte die Tacoio.pm editeren ?

Alt
[quote]
sub _get_files_in_dir {
my $args = shift;
my $dir = \$args->{'dir'};
my $p = \$args->{'pattern'};
my $pattern = q{*};
if ( ${$p} ) { $pattern = ${$p} ; }
my @files ;

foreach my $f (bsd_glob "${$dir}/$pattern") {
  push @files,$f;
}
[/quote]

neu

[quote]
sub _get_files_in_dir {
my $args = shift;
my $dir = \$args->{'dir'};
my $p = \$args->{'pattern'};
my $pattern = q{*};
if ( ${$p} ) { $pattern = ${$p} ; }
my @files ;

foreach my $f (bsd_glob "${$dir}/$pattern") {
  if ( $f =~ /^.{1,2}$/smx ) {next ; }
  push @files,$f;
}
[/quote]

holger

**Comment by clausmuus** [comment]
Also nur das if Statement hinzufügen.

@TimUx,
ich hab das Paket transcode-beta zum testen erstellt, dass die Änderung enthält.

Claus

**Comment by TimUx** [comment]
Hi Holger, Hi Claus,
ok ich teste dann am WE mal das Transcode-Beta in der MLD 5.1 Testing und berichte.  ;-)

Gruß Timo

**Comment by TimUx** [comment]
Hallo zusammen,
das Problem scheint noch nicht behoben zu sein.

Außerdem ist ein neues hinzu gekommen, wenn ich einen "prepare_traco_ts" starte.

```
combine_ts]got 25 from _getfps
[combine_ts]TS Files in /mnt/data/tv/Pacific_Rim/2015-12-26.20.10.6-0.rec
[DEBUG][combine_ts]get Byte Positions based on marks
[combine_ts]cut -> 0 time in sek -> 277 || frame -> 6948 || byteposition start -> 336866108 in File 1 stop -> 609599212 in File 2
[combine_ts]cut -> 1 time in sek -> 2992 || frame -> 74812 || byteposition start -> 1293384540 in File 2 stop -> 748002744 in File 3
[combine_ts]cut -> 2 time in sek -> 5029 || frame -> 125736 || byteposition start -> 1351800088 in File 3 stop -> 828037916 in File 4
[combine_ts]cut -> 3 time in sek -> 6893 || frame -> 172344 || byteposition start -> 1369550108 in File 4 stop -> 992853004 in File 5
[combine_ts]cut -> 4 time in sek -> 8890 || frame -> 222252 || byteposition start -> 1601932208 in File 5 stop -> 482141980 in File 6
Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/Traco/Tracoio.pm line 298.
[combine_ts]proccess  ***1 != 2 
Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/Traco/Tracoio.pm line 348.
[_cutfile]cut in /mnt/data/tv/Pacific_Rim/2015-12-26.20.10.6-0.rec file  ( start = 336866108 / stop =  )
[_cutfile] can't open  ... No such file or directory
 at /usr/bin/tracosrv.pl line 328.
seek() on closed filehandle $FH at /usr/share/perl5/Traco/Tracoio.pm line 353.
read() on closed filehandle $FH at /usr/share/perl5/Traco/Tracoio.pm line 354.
[_cutfile]can´t close  Bad file descriptor
 at /usr/bin/tracosrv.pl line 328.
[_cutfile]cut file  proccessed
Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/Traco/Tracoio.pm line 298.
[combine_ts]proccess  ***1+1 == 2 
[_cutfile]cut in /mnt/data/tv/Pacific_Rim/2015-12-26.20.10.6-0.rec file  ( start = 0 / stop = 609599212 )
[_cutfile] can't open  ... No such file or directory
 at /usr/bin/tracosrv.pl line 328.
seek() on closed filehandle $FH at /usr/share/perl5/Traco/Tracoio.pm line 353.
read() on closed filehandle $FH at /usr/share/perl5/Traco/Tracoio.pm line 354.
[_cutfile]can´t close  Bad file descriptor
 at /usr/bin/tracosrv.pl line 328.
[_cutfile]cut file  proccessed
```
Gruß Timo
